[package]
name = "oxipng"
version = "0.1.0"
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
oxipng = { version = "2.2.2", default-features = false }
wasm-bindgen = "0.2.48"

[profile.release]
lto = true
opt-level = "s"

[patch.crates-io]
oxipng = { git = "https://github.com/RReverser/oxipng.git", branch = "wasm" }
